name: SonarLint.Rystem.OpenAi
on:
  push:
    branches:
      - master
  issue_comment:
    types: [created, edited, deleted]
jobs:
  analyze:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, '/sonar') 
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 1.11
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
            path: ~\sonar\cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
            path: .\.sonar\scanner
            key: ${{ runner.os }}-sonar-scanner
            restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
            dotnet tool install --global dotnet-coverage
            New-Item -Path .\.sonar\scanner -ItemType Directory
            dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
            GITHUB_TOKEN: ${{ github.token }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
            .\.sonar\scanner\dotnet-sonarscanner begin /k:"KeyserDSoze_Rystem.OpenAi" /o:"keyserdsoze" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
            dotnet build "src/Rystem.OpenAi.Api/Rystem.OpenAi.Api.csproj" -c Debug
            dotnet test "src/Rystem.OpenAi.Test/Rystem.OpenAi.Test.csproj" -c Debug --no-build /p:CollectCoverage=true /p:CoverletOutput=$root\coverage /p:CoverletOutputFormat=opencover
            .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"